
version: '3.8'

services:
  rank-choice-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    container_name: rank-choice-voting-app
    environment:
      - NODE_ENV=production
