
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=/api
      - VITE_BASE_URL=${BASE_URL:-}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    # Add health check for frontend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:8080,http://frontend:80,http://frontend,*
      - DEBUG=express:*
      - LOG_LEVEL=debug
      - BASE_URL=${BASE_URL:-}
    restart: on-failure
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # Add these options to prevent disconnects
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  app-network:
    driver: bridge
